accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path("register/", accounts_views.RegisterView.as_view(), name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("library.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path

from .views import (BookFilterAuthorView, BookFilterCateforyView,
                    BookFilterNameView, BookFilterPublisherView, BookListView,
                    BookSearchView, MyBookListView)

app_name = "library"

urlpatterns = [
    path("", BookListView.as_view(), name="book_list"),
    path("mybooks/", MyBookListView.as_view(), name="mybooks"),
    path("bookname/<str:name>/", BookFilterNameView.as_view(), name="name_filter"),
    path(
        "category/<str:cat_name>/",
        BookFilterCateforyView.as_view(),
        name="category_filter",
    ),
    path(
        "author/<str:author_name>/",
        BookFilterAuthorView.as_view(),
        name="author_filter",
    ),
    path(
        "publisher/<str:pub_name>/",
        BookFilterPublisherView.as_view(),
        name="publisher_filter",
    ),
    path("search/<str:keyword>/", BookSearchView.as_view(), name="search"),
]

library/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _


class CommonInfo(models.Model):
    """Abstract base class for models common info"""

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Author(CommonInfo):
    """Books author"""

    full_name = models.CharField(max_length=255)

    def __str__(self):
        return self.full_name


class Publisher(CommonInfo):
    """Books publisher"""

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Category(CommonInfo):
    """Books category"""

    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Book(CommonInfo):
    """Book model to store books data"""

    name = models.CharField(max_length=255)
    image = models.ImageField(default="default.jpg", upload_to="book_images")
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.RESTRICT)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Borrow(CommonInfo):
    """Store borrowing data"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="borrowed")
    start_at = models.DateTimeField(default=now)
    end_at = models.DateTimeField()

    def clean(self):
        super().clean()
        # Don't allow end_at before start_at
        if self.end_at < self.start_at:
            raise ValidationError(_("end_at should not be before start_at"))
        # Don't borrow a book that borrowed by another user
        borrows = Borrow.objects.filter(book=self.book)
        if borrows:
            latest_borrow = borrows.latest("end_at")
            if (self.start_at < latest_borrow.end_at) and (
                self.user != latest_borrow.user
            ):
                raise ValidationError(
                    _(
                        f"This book is borrowed bofore by {latest_borrow.user.username} user.\
                            This user will bring back the book at {latest_borrow.end_at}."
                    )
                )

    def __str__(self):
        return self.book.name

library/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView

from .models import Author, Book, Borrow, Category, Publisher


class BookListView(LoginRequiredMixin, ListView):
    """
    A class based view for showing a list of available tasks.
    """

    model = Book
    context_object_name = "books"
    template_name = "library/book_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super(BookListView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        context["authors"] = Author.objects.all()
        context["publishers"] = Publisher.objects.all()
        return context


class MyBookListView(LoginRequiredMixin, ListView):
    """
    A class based view for showing a list of borrowed books to the user.
    """

    model = Borrow
    context_object_name = "borrowed_books"
    template_name = "library/my_books.html"

    def get_queryset(self):
        return Borrow.objects.filter(user=self.request.user)


class BookFilterNameView(LoginRequiredMixin, ListView):
    """
    A class based view to filter the books based on name.
    """

    model = Book
    context_object_name = "books"
    template_name = "library/book_list.html"

    def get_queryset(self):
        return Book.objects.filter(name__icontains=self.kwargs["name"]).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super(BookFilterNameView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        context["authors"] = Author.objects.all()
        context["publishers"] = Publisher.objects.all()
        return context


class BookFilterCateforyView(LoginRequiredMixin, ListView):
    """
    A class based view to filter the books based on a category.
    """

    model = Book
    context_object_name = "books"
    template_name = "library/book_list.html"

    def get_queryset(self):
        category = get_object_or_404(Category, name=self.kwargs["cat_name"])
        return Book.objects.filter(categories=category)

    def get_context_data(self, *args, **kwargs):
        context = super(BookFilterCateforyView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        context["authors"] = Author.objects.all()
        context["publishers"] = Publisher.objects.all()
        return context


class BookFilterAuthorView(LoginRequiredMixin, ListView):
    """
    A class based view to filter the books based on an auhtor.
    """

    model = Book
    context_object_name = "books"
    template_name = "library/book_list.html"

    def get_queryset(self):
        return Book.objects.filter(
            authors__full_name__icontains=self.kwargs["author_name"]
        ).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super(BookFilterAuthorView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        context["authors"] = Author.objects.all()
        context["publishers"] = Publisher.objects.all()
        return context


class BookFilterPublisherView(LoginRequiredMixin, ListView):
    """
    A class based view to filter the books based on a publisher.
    """

    model = Book
    context_object_name = "books"
    template_name = "library/book_list.html"

    def get_queryset(self):
        return Book.objects.filter(
            publisher__name__icontains=self.kwargs["pub_name"]
        ).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super(BookFilterPublisherView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        context["authors"] = Author.objects.all()
        context["publishers"] = Publisher.objects.all()
        return context


class BookSearchView(LoginRequiredMixin, ListView):
    """
    A class based view to searching on the books.
    """

    model = Book
    context_object_name = "books"
    template_name = "library/book_list.html"

    def get_queryset(self):
        keyword = self.kwargs["keyword"]
        result = Book.objects.filter(
            Q(name__icontains=keyword)
            | Q(publisher__name__icontains=keyword)
            | Q(authors__full_name__icontains=keyword)
            | Q(categories__name__icontains=keyword)
        )
        return result.distinct()

    def get_context_data(self, *args, **kwargs):
        context = super(BookSearchView, self).get_context_data(*args, **kwargs)
        context["categories"] = Category.objects.all()
        context["authors"] = Author.objects.all()
        context["publishers"] = Publisher.objects.all()
        return context

library/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html
  lang="en"
  data-footer="true"
  data-override='{"attributes": {"placement": "vertical","layout": "fluid", "color": "light-teal", "behaviour": "pinned"}, "showSettings":false, "storagePrefix": "starter-project"}'
>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>Library Management System</title>
    <meta name="description" content="Ecommerce Product Filters Page" />
    <!-- Favicon Tags Start -->
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="{% static 'library/img/favicon/apple-touch-icon-57x57.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'library/img/favicon/apple-touch-icon-114x114.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'library/img/favicon/apple-touch-icon-72x72.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'library/img/favicon/apple-touch-icon-144x144.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="{% static 'library/img/favicon/apple-touch-icon-60x60.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="{% static 'library/img/favicon/apple-touch-icon-120x120.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="{% static 'library/img/favicon/apple-touch-icon-76x76.png' %}"/>
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="{% static 'library/img/favicon/apple-touch-icon-152x152.png' %}"/>
    <link rel="icon" type="image/png" href="{% static 'library/img/favicon/favicon-196x196.png' %}"sizes="196x196" />
    <link rel="icon" type="image/png" href="{% static 'library/img/favicon/favicon-96x96.png' %}"sizes="96x96" />
    <link rel="icon" type="image/png" href="{% static 'library/img/favicon/favicon-32x32.png' %}"sizes="32x32" />
    <link rel="icon" type="image/png" href="{% static 'library/img/favicon/favicon-16x16.png' %}"sizes="16x16" />
    <link rel="icon" type="image/png" href="{% static 'library/img/favicon/favicon-128.png' %}"sizes="128x128" />
    <meta name="application-name" content="&nbsp;" />
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="{% static 'library/img/favicon/mstile-144x144.png' %}"/>
    <meta name="msapplication-square70x70logo" content="{% static 'library/img/favicon/mstile-70x70.png' %}"/>
    <meta name="msapplication-square150x150logo" content="{% static 'library/img/favicon/mstile-150x150.png' %}"/>
    <meta name="msapplication-wide310x150logo" content="{% static 'library/img/favicon/mstile-310x150.png' %}"/>
    <meta name="msapplication-square310x310logo" content="{% static 'library/img/favicon/mstile-310x310.png' %}"/>
    <!-- Favicon Tags End -->
    <!-- Font Tags Start -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'library/font/CS-Interface/style.css' %}"/>
    <!-- Font Tags End -->
    <!-- Vendor Styles Start -->
    <link rel="stylesheet" href="{% static 'library/css/vendor/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'library/css/vendor/OverlayScrollbars.min.css' %}"/>

    <!-- Vendor Styles End -->
    <!-- Template Base Styles Start -->
    <link rel="stylesheet" href="{% static 'library/css/styles.css' %}"/>
    <!-- Template Base Styles End -->

    <link rel="stylesheet" href="{% static 'library/css/main.css' %}"/>
    <script src="{% static 'library/js/base/loader.js' %}"></script>
  </head>

  <body>
    <div id="root">
      <div id="nav" class="nav-container d-flex">
        <div class="nav-content d-flex">
          <!-- Logo Start -->
          <div class="logo position-relative">
            <a href="{% url 'library:book_list' %}">
              <!-- Logo can be added directly -->
              <!-- <img src="{% static 'library/img/logo/fanavaran.png" alt="logo" /> -->

              <!-- Or added via css to provide different ones for different color themes -->
              <div class="img"></div>
            </a>
          </div>
          <!-- Logo End -->

          <!-- User Menu Start -->
          <div class="user-container d-flex">
            <a href="#" class="d-flex user position-relative" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img class="profile" alt="profile" src="{% static 'library/img/profile/profile.jpg' %}"/>
              <div class="name">{{ user.username }}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-end user-menu wide">
              <div class="row mb-3 ms-0 me-0">
                <div class="col-12 ps-1 mb-2">
                  <div class="text-extra-small text-primary">ACCOUNT</div>
                </div>
                <div class="col-6 ps-1 pe-1">
                  <ul class="list-unstyled">
                    <li>
                      <a href="#">User Info</a>
                    </li>
                    <li>
                      <a href="#">Preferences</a>
                    </li>
                    <li>
                      <a href="#">Calendar</a>
                    </li>
                  </ul>
                </div>
                <div class="col-6 pe-1 ps-1">
                  <ul class="list-unstyled">
                    <li>
                      <a href="#">Security</a>
                    </li>
                    <li>
                      <a href="#">Billing</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="row mb-1 ms-0 me-0">
                <div class="col-12 p-1 mb-2 pt-2">
                  <div class="text-extra-small text-primary">APPLICATION</div>
                </div>
                <div class="col-6 ps-1 pe-1">
                  <ul class="list-unstyled">
                    <li>
                      <a href="#">Themes</a>
                    </li>
                    <li>
                      <a href="#">Language</a>
                    </li>
                  </ul>
                </div>
                <div class="col-6 pe-1 ps-1">
                  <ul class="list-unstyled">
                    <li>
                      <a href="#">Devices</a>
                    </li>
                    <li>
                      <a href="#">Storage</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="row mb-1 ms-0 me-0">
                <div class="col-12 p-1 mb-3 pt-3">
                  <div class="separator-light"></div>
                </div>
                <div class="col-6 ps-1 pe-1">
                  <ul class="list-unstyled">
                    <li>
                      <a href="#">
                        <i data-acorn-icon="help" class="me-2" data-acorn-size="17"></i>
                        <span class="align-middle">Help</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i data-acorn-icon="file-text" class="me-2" data-acorn-size="17"></i>
                        <span class="align-middle">Docs</span>
                      </a>
                    </li>
                  </ul>
                </div>
                <div class="col-6 pe-1 ps-1">
                  <ul class="list-unstyled">
                    <li>
                      <a href="#">
                        <i data-acorn-icon="gear" class="me-2" data-acorn-size="17"></i>
                        <span class="align-middle">Settings</span>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'accounts:logout' %}">
                        <i data-acorn-icon="logout" class="me-2" data-acorn-size="17"></i>
                        <span class="align-middle">Logout</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- User Menu End -->

          <!-- Icons Menu Start -->
          <ul class="list-unstyled list-inline text-center menu-icons">
            <li class="list-inline-item">
              <a href="#" id="pinButton" class="pin-button">
                <i data-acorn-icon="lock-on" class="unpin" data-acorn-size="18"></i>
                <i data-acorn-icon="lock-off" class="pin" data-acorn-size="18"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#" id="colorButton">
                <i data-acorn-icon="light-on" class="light" data-acorn-size="18"></i>
                <i data-acorn-icon="light-off" class="dark" data-acorn-size="18"></i>
              </a>
            </li>
          </ul>
          <!-- Icons Menu End -->

          <!-- Menu Start -->
          <div class="menu-container flex-grow-1">
            <ul id="menu" class="menu">
              <li>
                <a href="{% url 'library:book_list' %}">
                  <i data-acorn-icon="books" class="icon" data-acorn-size="18"></i>
                  <span class="label">Library</span>
                </a>
              </li>
              <li>
                <a href="{% url 'library:mybooks' %}">
                  <i data-acorn-icon="book" class="icon" data-acorn-size="18"></i>
                  <span class="label">My Books</span>
                </a>
              </li>
            </ul>
          </div>
          <!-- Menu End -->

          <!-- Mobile Buttons Start -->
          <div class="mobile-buttons-container">
            <!-- Menu Button Start -->
            <a href="#" id="mobileMenuButton" class="menu-button">
              <i data-acorn-icon="menu"></i>
            </a>
            <!-- Menu Button End -->
          </div>
          <!-- Mobile Buttons End -->
        </div>
        <div class="nav-shadow"></div>
      </div>

      <main>
        <div class="container">
          <!-- Title and Top Buttons Start -->
          <div class="page-title-container">
            <div class="row">
              <!-- Title Start -->
              {% block title %}{% endblock title %}
              <!-- Title End -->
            </div>
          </div>
          <!-- Title and Top Buttons End -->

          <!-- Content Start -->
          {% block content %}{% endblock content %}
          <!-- Content End -->
        </div>

        <!-- Filter Modal Start -->
        {% block filter %}{% endblock filter %}
        <!-- Filter Modal End -->
      </main>

      <!-- Layout Footer Start -->
      <footer>
        <div class="footer-content">
          <div class="container">
            <div class="row">
              <div class="col-12 col-sm-6">
                <p class="mb-0 text-muted text-medium">MRA-AK@2022</p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!-- Layout Footer End -->
    </div>

    <!-- Vendor Scripts Start -->
    <script src="{% static 'library/js/vendor/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'library/js/vendor/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'library/js/vendor/OverlayScrollbars.min.js' %}"></script>
    <script src="{% static 'library/js/vendor/autoComplete.min.js' %}"></script>
    <script src="{% static 'library/js/vendor/clamp.min.js' %}"></script>
    <script src="{% static 'library/icon/acorn-icons.js' %}"></script>
    <script src="{% static 'library/icon/acorn-icons-interface.js' %}"></script>
    <script src="{% static 'library/icon/acorn-icons-commerce.js' %}"></script>
    <script src="{% static 'library/icon/acorn-icons-learning.js' %}"></script>

    <script src="{% static 'library/js/vendor/jquery.barrating.min.js' %}"></script>

    <script src="{% static 'library/js/vendor/movecontent.js' %}"></script>

    <!-- Vendor Scripts End -->

    <!-- Template Base Scripts Start -->
    <script src="{% static 'library/js/base/helpers.js' %}"></script>
    <script src="{% static 'library/js/base/globals.js' %}"></script>
    <script src="{% static 'library/js/base/nav.js' %}"></script>
    <script src="{% static 'library/js/base/search.js' %}"></script>
    <script src="{% static 'library/js/base/settings.js' %}"></script>
    <!-- Template Base Scripts End -->
    
    <!-- Page Specific Scripts Start -->
    <script src="{% static 'library/js/common.js' %}"></script>
    <script src="{% static 'library/js/scripts.js' %}"></script>
    {% block script %}{% endblock %}
    <!-- Page Specific Scripts End -->
  </body>
</html>

library/templates/library/book_list.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% load custom_tags %}
{% load static %}

{% block title %}
    <!-- Title and Top Buttons Start -->
    <div class="page-title-container">
      <div class="row g-0">
        <div class="col-auto mb-2 mb-md-0 me-auto">
          <div class="w-auto sw-md-30">
            <h1 class="mb-0 pb-0 display-4" id="title">List of Books</h1>
          </div>
        </div>
        <div class="col-12 col-md-6 d-flex align-items-start justify-content-end justify-content-lg-start">
          <div class="me-lg-auto w-100 search-input-container border border-separator">
            <input class="form-control search" type="text" autocomplete="off" placeholder="Search" id="searchTxt" />
            <span id="searchBtn" class="search-magnifier-icon">
              <button data-acorn-icon="search"></button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <!-- Title and Top Buttons End -->
{% endblock title %}

{% block content %}
  <div class="row">
    <!-- Left Side Start -->
    <div class="col-12 col-lg-4 col-xl-3 d-none d-lg-block">
      <div class="card mb-5">
        <div class="card-body mb-n5" id="filterColumn">
          <!-- Content of this will be moved from #filterMoveContent div based on the responsive breakpoint.  -->
        </div>
      </div>
    </div>
    <!-- Left Side End -->

    <!-- Right Side Start -->
    <div class="col-12 col-lg-8 col-xl-9">
      <!-- Product Thumbnails Start -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-2 row-cols-xl-3 g-2 mb-5" id="productsCheckAll">
        {% for book in books %}
        <div class="col">
          <div class="card h-100">
            <a href="#">
              <img src="{{ book.image.url }}" class="card-img-top sh-30 mt-3" alt="book image" />
            </a>
            <div class="card-body pb-2">
              <h3 class="mb-0 d-flex justify-content-center">
                <a href="#" class="body-link lh-1-5 clamp-line" data-line="2">{{ book.name }}</a>
              </h3>
              <h6 class="mb-2 d-flex justify-content-center">by 
                {% for author in book.authors.all %}
                  {% if not forloop.first %}
                    {% if forloop.last %}
                    and
                    {% else %}
                    ,
                    {% endif %}
                  {% endif %}
                  {{ author.full_name|title }}
                {% endfor %}
              </h6>
            </div>
            <div class="mb-3 d-flex justify-content-center">
              {% if book|is_borrowed %}
              <button type="button" class="btn btn-light btn-lg btn-block">Borrowed</button>
              {% else %}
              <button type="button" class="btn btn-info btn-lg btn-block">Available</button>
              {% endif %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- Product Thumbnails End -->

    </div>
    <!-- Right Side End -->
  </div>
{% endblock content %}

{% block filter %}
  <div class="modal modal-left fade" id="filterModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Filters</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- Content of below will be moved to #filterColumn or back in here based on the data-move-breakpoint attribute below -->
          <!-- Content will be here if the screen size is smaller than lg -->
          <div id="filterMoveContent" data-move-target="#filterColumn" data-move-breakpoint="lg">

            <div class="mb-5">
              <p class="text-small text-muted mb-2">CATEGORY</p>
              {% for category in categories %}
              <div class="form-check">
                <li class="form-check-label"><a href="{% url 'library:category_filter' cat_name=category.name %}">{{ category|title }}</a></li>
              </div>
              {% endfor %}
            </div>

            <div class="mb-5">
              <p class="text-small text-muted mb-2">AUTHOR</p>
              {% for author in authors %}
              <div class="form-check">
                <li class="form-check-label"><a href="{% url 'library:author_filter' author_name=author.full_name %}">{{ author|title }}</a></li>
              </div>
              {% endfor %}
            </div>

            <div class="mb-5">
              <p class="text-small text-muted mb-2">PUBLISHER</p>
              {% for publisher in publishers %}
              <div class="form-check">
                <li class="form-check-label"><a href="{% url 'library:publisher_filter' pub_name=publisher.name %}">{{ publisher|title }}</a></li>
              </div>
              {% endfor %}
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock filter %}

{% block script %}
  <script src="{% static 'library/js/cs/checkall.js' %}"></script>
  <script src="{% static 'library/js/pages/storefront.filters.js' %}"></script>
  <script>
    const element = document.getElementById("searchBtn");
    element.addEventListener("click", myFunction);
    
    function myFunction() {
      var text = document.getElementById("searchTxt").value;
      if (text !== "") {
        var url = "{% url 'library:search' keyword='url_arg' %}"
        var new_url = url.replace('url_arg', text);
        location.href = new_url;
      }
    }
  </script>
{% endblock script %}

library/templates/library/my_books.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load static %}

{% block title %}
    <!-- Title and Top Buttons Start -->
    <div class="page-title-container">
      <div class="row g-0">
        <div class="col-auto mb-2 mb-md-0 me-auto">
          <div class="w-auto sw-md-30">
            <h1 class="mb-0 pb-0 display-4" id="title">Borrowed Books</h1>
          </div>
        </div>
        <div class="col-12 col-md-6 d-flex align-items-start justify-content-end justify-content-lg-start">
        </div>
      </div>
    </div>
    <!-- Title and Top Buttons End -->
{% endblock title %}

{% block content %}
  <div class="row">
    <!-- Right Side Start -->
    <div class="col-12 col-lg-8 col-xl-9">
      <!-- Product Thumbnails Start -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-2 row-cols-xl-3 g-2 mb-5" id="productsCheckAll">
        {% for borrow in borrowed_books %}
        <div class="col">
          <div class="card h-100">
            <a href="#">
              <img src="{{ borrow.book.image.url }}" class="card-img-top sh-22" alt="card image" />
            </a>
            <div class="card-body pb-2">
              <h3 class="mb-3 d-flex justify-content-center">
                <a href="#" class="body-link lh-1-5 clamp-line" data-line="2">{{ borrow.book.name }}</a>
              </h3>
              <h6 class="mb-1 d-flex">Start: {{ borrow.start_at|naturalday }} - {{ borrow.start_at.time }}</h6>
              <h6 class="mb-1 d-flex">End: {{ borrow.end_at|naturalday }} - {{ borrow.end_at.time }}</h6>
            </div>
            <div class="mb-3 d-flex justify-content-center">
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- Product Thumbnails End -->

    </div>
    <!-- Right Side End -->
  </div>
{% endblock content %}